module dfmm

# 1D / 2D Julia implementation of the unified dfmm framework.
#
# Design corpus:
#   HANDOFF.md
#   specs/01_methods_paper.pdf
#   design/04_action_note_v3_FINAL.pdf
#   specs/05_julia_ecosystem_survey.md
#
# Milestone 1 scope: a 1D Julia implementation reproducing the
# regression target at py-1d/. See HANDOFF.md "Milestone 1 plan" and
# reference/MILESTONE_1_PLAN.md for the phase-by-phase breakdown.
#
# Phase 1: Cholesky-sector variational integrator with externally
# supplied γ. See `src/cholesky_sector.jl` for the action and discrete
# EL system.
#
# Phase 2: full deterministic action L_det = ½ ẋ² + L_Ch on a
# multi-segment periodic Lagrangian-mass mesh, with bulk position x,
# velocity u, and frozen entropy s. See
# `reference/notes_phase2_discretization.md` and `src/discrete_action.jl`
# / `src/cholesky_sector.jl`'s `det_el_residual`.

# Field types live first so downstream files (including eos.jl) can
# refer to them via Mvv-method overloading.
include("types.jl")

# EOS is included before segment.jl so that segment.jl helpers
# (`total_energy`) and the Phase-2 EL residual can reach the
# `Mvv(J, s)` adiabat method.
include("eos.jl")

include("segment.jl")
include("discrete_transport.jl")
include("discrete_action.jl")
include("cholesky_sector.jl")
# Phase 5: deviatoric / P_⊥ BGK update (used by det_step!).
include("deviatoric.jl")
# Phase 5b: opt-in artificial viscosity (tensor-q) for shock capture.
include("artificial_viscosity.jl")
include("newton_step.jl")

# --- Phase 1 API ----------------------------------------------------------
export ChField, gamma_from_Mvv
export Segment, Mesh1D, single_segment_mesh
export D_t_q
export cholesky_one_step_action, cholesky_el_residual, cholesky_hamiltonian
export cholesky_step, cholesky_run

# --- Phase 2 API (multi-segment full deterministic) ------------------------
export DetField
export n_segments, vertex_mass, segment_length, segment_density,
       total_mass, total_momentum, total_energy,
       total_internal_energy, total_kinetic_energy
export discrete_action_sum, segment_cholesky_action, midpoint_strain, midpoint_J
export det_el_residual
export det_step!, det_run!, pack_state, pack_state!, unpack_state!

# --- Phase 5 API (deviatoric / P_⊥ BGK relaxation) -------------------------
export deviatoric_bgk_step, deviatoric_bgk_step_exponential,
       pperp_advect_lagrangian, bgk_relax_pressures, pperp_step

# --- Phase 5b API (opt-in artificial viscosity / tensor-q) -----------------
export compute_q_segment, q_kind_supported, q_active,
       Q_KIND_NONE, Q_KIND_VNR_LINEAR_QUADRATIC

# --- Track C/F infrastructure layer (Milestone 1, Agent C) -----------------
# Pure infrastructure modules: diagnostics, I/O, plotting, calibration.
# (eos.jl is included higher up so Phase-2 segment.jl can use it.)
include("diagnostics.jl")
include("io.jl")
include("calibration.jl")
include("plotting.jl")

# --- Track D stochastic primitives (Milestone 1, Agent D) ------------------
# Variance-gamma sampling, burst-statistics, self-consistency monitor.
# Will be wired into the integrator's stochastic injection in Phase 8.
include("stochastic.jl")
using .Stochastic

# Public re-exports for convenient REPL use; these are the entry points
# the milestone plan calls out for cross-track consumers.
export Mvv, gamma_from_state, Mvv_from_pressure, pressure_from_Mvv
export gamma_rank_indicator, realizability_marker,
       realizability_marker_from_Mvv, hessian_HCh, det_hessian_HCh
export save_state, load_state
export load_noise_model
export plot_profile, plot_phase_portrait, plot_diagnostics
export Stochastic,
       rand_variance_gamma,
       rand_variance_gamma!,
       pdf_variance_gamma,
       cdf_variance_gamma,
       burst_detect,
       estimate_gamma_shape,
       residual_kurtosis,
       gamma_shape_from_kurtosis,
       ks_test

# Tier-A initial-condition factories. Mirrors the six benchmarks listed
# in the methods paper §10.2; the corresponding HDF5 goldens are
# generated by `scripts/make_goldens.jl` and live under
# `reference/golden/`.
include("setups.jl")
export setup_sod, setup_cold_sinusoid, setup_steady_shock,
       setup_kmles_wavepool, setup_dust_in_gas, setup_eion

# Tier-A regression-scaffold: HDF5 golden loader. The full
# integrator-vs-golden comparison enters at Phase 5; this module
# lands the loader plumbing in advance.
include("regression.jl")
export load_tier_a_golden

end # module
