# heat_flux.jl
#
# Phase 7 — Heat-flux Lagrange-multiplier sector.
#
# ──────────────────────────────────────────────────────────────────────
# Why this exists.
# ──────────────────────────────────────────────────────────────────────
#
# The deterministic Lagrangian (methods paper §3.2, design/03_action_note_v2
# §3.2) carries a heat-flux sector
#
#     L_det ⊃ λ_Q (Q̇ + Q/τ - S_Q)
#
# where `Q` is the third velocity-moment central component
# (`Q = M_3 - ρ u^3 - 3 u P_xx`), `τ` is the BGK relaxation time
# (shared with the deviatoric / β sector), and `S_Q` is the
# Chapman-Enskog source. In the **hard-constraint** formulation
# `λ_Q` is a Lagrange multiplier enforcing `Q̇ + Q/τ = S_Q` exactly
# at each timestep, and `Q` becomes a derived dynamical variable
# evolving via that ODE — structurally identical to Phase-5's
# deviatoric-Π / β BGK relaxation.
#
# ──────────────────────────────────────────────────────────────────────
# Discretization choice (this file).
# ──────────────────────────────────────────────────────────────────────
#
# We adopt the same **post-Newton operator-split** discretization as
# Phase 5's β / P_⊥ updates: after the implicit-midpoint Newton step
# advances `(x, u, α, β)`, we apply a closed-form exponential to `Q`
# matching `py-1d/dfmm/schemes/cholesky.py` lines 154–169 exactly:
#
#     Q^{n+1} = Q^n · exp(-Δt/τ).
#
# This corresponds to `S_Q = 0` — i.e. the equilibrium target for `Q`
# in an isotropic Maxwellian is zero (any Maxwell-Boltzmann distribution
# has vanishing third central moment). The Chapman-Enskog source `S_Q
# ∝ -κ ∂_x T` enters only at higher Knudsen number (the kinetic-theory
# Fourier law), and py-1d's heat-flux closure does **not** include it
# — Q is dynamically generated by the M_3 flux divergence and the
# Liouville source, then relaxed to zero by BGK. We mirror that
# choice here for bit-equality with the regression target.
#
# This keeps the Newton degrees of freedom at 4N per timestep
# `(x, u, α, β)`; `Q` is updated separately as an advected scalar.
# In the inflow-outflow steady-shock setup `Q` is initialized to zero
# at every Tier-A IC (`src/setups.jl` `Q = zeros(N)`) and the only
# dynamics it sees are the BGK relaxation of any disturbance produced
# by the shock front — exactly matching py-1d's `Q_n * decay` line in
# the BGK loop.
#
# ──────────────────────────────────────────────────────────────────────
# Soft-constraint deferral (per v3 footnote).
# ──────────────────────────────────────────────────────────────────────
#
# v2 §3.2 also discusses a *soft-constraint* form with a trapping
# potential `V(Q)` that biases Q toward the equilibrium target. This
# is deferred to a future appendix per the v3 note's guidance. The
# hard-constraint form here is sufficient to reproduce dfmm Fig. 4
# Rankine-Hugoniot to the methods-paper §10.2 A.3 acceptance bar.
#
# References:
#   methods paper §3.2 (`L_det` definition with λ_Q term)
#   design/03_action_note_v2.tex §3.2 (Hamilton-Pontryagin form)
#   py-1d/dfmm/schemes/cholesky.py lines 154-169 (BGK Q decay)

"""
    heat_flux_bgk_step(Q_n, dt, τ) -> Q_np1

Hard-constraint exact-exponential BGK update for the heat flux `Q`
under `Q̇ + Q/τ = 0` (the `S_Q = 0` case appropriate for Maxwellian
relaxation; methods paper §3.2 hard-constraint form):

    Q^{n+1} = Q^n · exp(-Δt/τ).

Bit-identical to `py-1d/dfmm/schemes/cholesky.py` line 169
(`Q_new = Q_n * decay` with `decay = np.exp(-dt/tau)`).

Stable for any `Δt/τ > 0`. Returns a scalar of the same numeric type
as `Q_n`, AD-friendly under ForwardDiff `Dual`.
"""
heat_flux_bgk_step(Q_n::Real, dt::Real, τ::Real) =
    Q_n * exp(-dt / τ)


"""
    heat_flux_advect_lagrangian(Q_n, ρ_n, ρ_np1) -> Q_np1_transport

Transport of the heat flux `Q` under the hyperbolic (convective)
step in Lagrangian coordinates. The Eulerian conservation law for
`Q` (third central moment) advects with the bulk flow at leading
order; in Lagrangian-mass coordinates `D_t (Q/ρ) = 0` matches the
Lagrangian-frame transport of the perpendicular pressure (see
`pperp_advect_lagrangian` in deviatoric.jl). So

    Q^{n+1, transport} = Q^n · ρ^{n+1}/ρ^n.

This is the post-Newton transport step applied before the BGK
relaxation, mirroring the Phase-5 P_⊥ update structure for parity
across the (β, P_⊥, Q) sectors.
"""
heat_flux_advect_lagrangian(Q_n::Real, ρ_n::Real, ρ_np1::Real) =
    Q_n * ρ_np1 / ρ_n


"""
    heat_flux_step(Q_n, ρ_n, ρ_np1, dt, τ) -> Q_np1

One operator-split heat-flux update:

  1. Lagrangian transport: `Q_transport = Q_n · ρ_np1/ρ_n`.
  2. BGK relaxation: `Q_np1 = Q_transport · exp(-Δt/τ)`.

Returns the new heat flux after both substeps. In the τ → 0 limit
the relaxation is instantaneous and `Q → 0` (Euler-like, no heat
conduction). In the τ → ∞ limit BGK is off and `Q` simply advects
with the bulk flow (collisionless / free-streaming).

This matches py-1d's split-step physics applied to the Lagrangian
frame: py-1d's `cholesky.py` integrates `M_3` through the HLL flux
divergence and then applies `Q_new = Q_n * decay`. In the Julia
variational integrator the M_3 flux divergence is replaced by the
Lagrangian transport of `Q/ρ` (advection) — the conserved quantity
along Lagrangian trajectories in the absence of a Chapman-Enskog
source is `Q/ρ`, not `Q` itself.
"""
function heat_flux_step(Q_n::Real, ρ_n::Real, ρ_np1::Real,
                        dt::Real, τ::Real)
    Q_transport = heat_flux_advect_lagrangian(Q_n, ρ_n, ρ_np1)
    return heat_flux_bgk_step(Q_transport, dt, τ)
end
